name: Build and Deploy

on:
  push:
    branches:
      - master
  schedule:
    - cron: '49 2 * * 1-5'  # 2:49 on weekdays
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    env:
      FAKE_DETAILED_ERRORS: 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Configure secrets
        run: dotnet run -- -t configure -- ${{ secrets.GH_CLIENT_ID }} ${{ secrets.GH_CLIENT_SECRET }}

      - name: Generate site
        run: dotnet run -- -t generate

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: public/

  deploy:
    name: Netlify Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: public
          path: public

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: ./public
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-pull-request-comment: false
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
